apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
      name: api
    {{- if .Values.console.enabled }}
    - port: {{ .Values.service.console.port }}
      targetPort: {{ .Values.service.console.targetPort }}
      protocol: TCP
      name: console
    {{- end }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
---
{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-console
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.console.port }}
      targetPort: {{ .Values.service.console.targetPort }}
      protocol: TCP
      name: console
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
{{- end }} 