---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hetzner-csi-default
  annotations:
    # Set this to true if you want Hetzner CSI to be the default storage class
    # storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.hetzner.cloud
parameters:
  csi.storage.k8s.io/fstype: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hetzner-csi-fast
provisioner: csi.hetzner.cloud
parameters:
  csi.storage.k8s.io/fstype: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hetzner-csi-retain
provisioner: csi.hetzner.cloud
parameters:
  csi.storage.k8s.io/fstype: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain 