# NOTE: Search + Replace k8s.stormix.dev with your own Cloudflared domain before enabling
tunnel: reclaim-the-stack
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true

ingress:
  - hostname: stream-stats.k8s.stormix.dev
    service: http://stream-stats-web.default.svc
  - hostname: argocd.k8s.stormix.dev
    service: https://argocd-server.argocd.svc
    originRequest:
      noTLSVerify: true
  - hostname: grafana.k8s.stormix.dev
    service: http://monitoring-grafana.monitoring.svc
  # This rule matches any traffic which didn't match a previous rule and returns 404:
  - service: http_status:404
