image: teamspeak:latest

replicaCount: 1

service:
  type: NodePort
  ports:
    voice:
      port: 9987
      targetPort: 9987
      nodePort: 30987
      protocol: UDP
    query:
      port: 10011
      targetPort: 10011
      nodePort: 30011
      protocol: TCP
    file:
      port: 30033
      targetPort: 30033
      nodePort: 30033
      protocol: TCP

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

env:
  - name: TS3SERVER_LICENSE
    value: "accept"

nodeSelector: {}
tolerations: []
affinity: {}

securityContext:
  runAsUser: 9987
  runAsGroup: 9987
  fsGroup: 9987

podSecurityContext:
  runAsNonRoot: true 