deployments: {}
resources:
  rabbitmq:
    replicas: 3
    memory: 512Mi
    cpu: 250m
    disk: 1Gi
    config:
      additionalConfig: |
        log.console.level = info
        vm_memory_high_watermark.relative = 0.7
  redis:
    sentinels: 3
    replicas: 2
    memory: 100Mi # must use Gi or Mi format
    cpu: 250m
    disk: 500Mi
  postgres:
    replicas: 2
    memory: 1Gi
    cpu: 1
    disk: 10Gi
    # Tip: generate configuration based on CPU / RAM settings at https://pgtune.leopard.in.ua/
    config:
      max_connections: "40"
      shared_buffers: 256MB
      effective_cache_size: 768MB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 7864kB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 3276kB
      min_wal_size: 1GB
      max_wal_size: 4GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: top
envFrom: []
env:
  - { name: REDIS_URL, value: "redis://huginn-redis-master.default.svc:6379" }
  - { name: DATABASE_URL, valueFrom: { secretKeyRef: { name: huginn-app, key: uri } } }
  - { name: RABBITMQ_URL, valueFrom: { secretKeyRef: { name: huginn-app, key: url } } }
