image: stormix/deadlock-mods-api:latest
deployments:
  web:
    replicas: 3
    memory: 250Mi
    cpu: 50m
    env:
      - name: WEB_CONCURRENCY
        value: "2"
    readinessProbePath: /
    port: 9000
    command: bun run src/index.ts
envFrom:
  - secretRef:
      name: deadlock-mod-manager # Create a dedicated application secret with k secrets:create deadlock-mod-manager
