image: stormix/deadlock-mods-api:latest
deployments:
  web:
    replicas: 3
    memory: 512Mi
    cpu: 100m
    env:
      - name: WEB_CONCURRENCY
        value: "2"
    readinessProbePath: /
    port: 9000
    command: bun run src/index.ts
resources:
envFrom:
  - secretRef:
      name: deadlock-mod-manager # Create a dedicated application secret with k secrets:create deadlock-mod-manager
env:
  - { name: DATABASE_URL_OLD, valueFrom: { secretKeyRef: { name: deadlock-mod-manager-app, key: uri } } }
