apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAo1YbgpTrPbN0rNW/8+rcz2WMoQGplU0xFMVZcf52M7+C09FmkqksxXYlH/cE/Q3steiV7YPHvKChEkQgj6ynJ74Sse4TCaVKuL58TkZCFHvBFJ3JLPcVkGdvgkgURWE/aQRIfJhmfzzrsDxBXmcOk7DTFf7xV2shUexqL5FKNhkYgryoQ1VqN7nhsutH/ewQkQksfsM5WfxX2jcmo2GUoCoPwfOXCBVhHj5uonxeMhc6ycKrs7dWLW1TO7A3OuCgAXlKKWxo+DOlGp3331eg+n7i0I7uydtNoCeQkhWTZzj8RO0KUWk/w/2N/uSlS8F9AtpYxlxG/fbWzW05XImc97HbQ6rYILFaKdamsjsZCsGHv0xmyZ03PNmeTZ4BbGnPU3nCQACrielKHli5rhyqoAU9sR+VzbgCBj9CmwFCo7vGxil3AQkDDrf+1JItJOxhdRZfUO9Op2PqiUfxMa1LKfnrTF7csZyEeKidNm8lufSe6AhMiS4u2J7fkAUF6D02TFpkIryvhY3P7+NTrpFeBWgymFol9dfWTpH0gQuyRskHwApmUejB+CIaW3VE9mcoTtTo0QNArz1HUBBTdmECESI4uTheEJF5DaphcWvqdbCsfNXdR1v9y4aFYc5sleqp/zcGSWZ2d46CTYAKGAszXDLWlSSZSCDwormuikRQALgO2EN5oGSEH/efL4UR8qke1oNLhAjgjPv5W5mWM1Wa0eFs3ovEIfNWwjZ34y85DaODHHXaRLEsX9gBsEGIgdZtiqHkY1X7l9PMQpS4F15yJsuz8L49kz5EYJnX4RJlk6KX2QuN5tDGHoZRcUgxdYMrMItzzWBoo2HX1gTOpxjmPdataH7dyQAqDuwR3NSHsLYcTkeqZisjSDqxDQlmxO2MRV//CXF1uTTySxtVBw5d9xw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
status: {}

