---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBsemmKxha8nmOF++yNId44x6N2nzqgjtSMyvnDmZ/fwEHNLbBpu8uvQPYIUnXcOtxVJlAPd6GeCZApDra8kBpgxII9tZeN3vevC0VM4otRNz9HuoGknpO2KoTB/vbk0ikExah5YcLT+eGSMuX5D6vyGMqrfDPcBYj2AP7r2VaUCq997ApBRtXIL+IiD1cw2VGymrFqO1kne5CtxOSwFSXmgYyQ4qq5aQe7QnJkQiPSJFszqqUu1ZU/7n2yHF8qtqVgd4DvNMmHpWZuoMRGODgd6513g9ZeH9wA2jx6fuLlbhRSxM65YRMSDMFRPKepTioNmwKekJsbdv1ZKxhPWhOf4UDidJ15pVb0LwJp77WUBjApGDN+nBo7CGFz2I4lOE/LaHkiexBJHNhUiVnAx2YX7HIQnXqEVip0WfGnlMDhnkKci+RzNt0I74pm4u8Xo/wvHw1Kf2o0ScHKTTO52S5jbzgp9ZvB0O9wW2rvKuETwmGbGSaMY6XU1skAUjVicI2W2vfLHMXkPdRBdKOHDoKI4xj1x9ZVQ/KoBT3rSXncSmEcfGlNDGJl3hr1LyHYUf02bSjZVFgmMax9+/koH+3uOVrV0yZT6ircVmYwiCLRFOTRL3fcOtnoqjjL5+86B/13D5XucCCFa+T/MGiG4EMSPq6R20TjKvXD5j4oqU+Qtmf4ZaTQCDrBj/FwnmHRk/BnkekjGKBG00V7KyyRvKnmhpVnYmExqbd/93DCR27yOUNficTDiSlIl5qucsqhTi+MBQb4RYieMniENXxfbaUOc4LWarQ9KZlW7IdaQtPUxzSJtBWxLsf7FCWZv+9INr5hui60IZO217vZfUSJlebyJim0IakppRcvCGToTNvchEGfmZ5+HFVESEVAlwMu1wbCT2NO+xohYRN3cANgB4YM2R6H2Nj+wZZfLwWa3ZKJ
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
