image: stormix/mlc-server:latest
deployments:
  web:
    replicas: 3
    memory: 250Mi
    cpu: 50m
    env:
      - name: WEB_CONCURRENCY
        value: "2"
    readinessProbePath: /
    port: 3000
    command: bun run --preload src/instrument.ts src/index.ts
envFrom:
  - secretRef:
      name: mlc-server # Create a dedicated application secret with k secrets:create mlc-server
