image: stormix/higherlower-live:latest
deployments:
  web:
    replicas: 1
    memory: 512Mi
    cpu: 250m
    env:
      - name: WEB_CONCURRENCY
        value: "2"
    readinessProbePath: /
    port: 3000
    command: bun run server/index.mjs
resources:
  postgres:
    replicas: 1
    memory: 1Gi
    cpu:  250m
    disk: 1Gi
    config:
      max_connections: "40"
      shared_buffers: 256MB
      effective_cache_size: 768MB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 7864kB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 3276kB
      min_wal_size: 1GB
      max_wal_size: 4GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: top
envFrom:
  - secretRef:
      name: higherlower-live # Create a dedicated application secret with k secrets:create higherlower-live
env:
  - { name: DATABASE_URL, valueFrom: { secretKeyRef: { name: higherlower-live-app, key: uri } } }
