image: stormix/stream-crush:latest
deployments:
  webWorker:
    replicas: 1
    memory: 2024Mi
    cpu: 500m
    command: bun run src/worker.ts
  web:
    replicas: 1
    memory: 2024Mi
    cpu: 500m
    readinessProbePath: /
    port: 3000
    command: bun run src/index.ts
resources:
  redis:
    sentinels: 1
    replicas: 1
    memory: 100Mi
    cpu: 250m
    disk: 500Mi 
env: 
  - { name: REDIS_URL, value: "redis://stream-crush-redis-master.default.svc:6379" }
envFrom:
  - secretRef:
      name: stream-crush

