apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hetzner-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/hetzner-csi
    repoURL: https://github.com/stormix/infrastructure.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
      - ServerSideApply=true 