deployments: {}
resources:
  postgres:
    replicas: 1
    memory: 1Gi
    cpu: 1
    disk: 1Gi
    # Tip: generate configuration based on CPU / RAM settings at https://pgtune.leopard.in.ua/
    config:
      max_connections: "40"
      shared_buffers: 256MB
      effective_cache_size: 768MB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 7864kB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 3276kB
      min_wal_size: 1GB
      max_wal_size: 4GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: top
envFrom: []
env:
  - { name: DATABASE_URL, valueFrom: { secretKeyRef: { name: stream-stats-app, key: uri } } }
