image: stormix/squad-streams:latest
deployments:
  web:
    replicas: 1
    readinessProbePath: /api/health
    port: 3000
    command: bun run src/index.tsx
envFrom:
  - secretRef:
      name: kick-together

