image: stormix/squad-streams:latest
deployments:
  web:
    replicas: 5
    memory: 1024Mi
    cpu: 100m
    readinessProbePath: /api/health
    port: 3000
    command: bun run src/index.tsx
envFrom:
  - secretRef:
      name: kick-together

