image: stormix/twitch-stalker-server:latest
deployments:
  web:
    replicas: 3
    memory: 512Mi
    cpu: 100m
    env:
      - name: WEB_CONCURRENCY
        value: "2"
    readinessProbePath: /api/health
    port: 3000
    command: bun start
resources:
  redis:
    sentinels: 3
    replicas: 2
    memory: 100Mi # must use Gi or Mi format
    cpu: 100m
    disk: 500Mi
envFrom:
  - secretRef:
      name: twitch-stalker # Create a dedicated application secret with k secrets:create twitch-stalker
env:
  - { name: REDIS_URL, value: "redis://twitch-stalker-redis-master.default.svc:6379" }
