---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deadlock-mod-manager
  namespace: default
spec:
  encryptedData:
    NODE_ENV: AgCbz9cmCKVloqTu9jS572YlaUaN5Owu2npB+Grnd/lviwm3MsfF4XiMcT8cbl8Gg3qUR5AWh8mVzvuHq3xJDKJpwqDI23kM1Dx/jBj+2JdHoYSxTcg+93KjbmwyYduhFl8tfZqxNKzj2jclb97NtUSZ3bPvLQEUouT9mXrfWycR1x4DG7FI+nruLOTPY9EFOwZK53c3S67ulwkInyR/QVE6R+KmuD81fp7I9H4tE4E8vV+tTKzuG+vqA2Ieet4UvZx2+H7Z8sI/4ixeB+h66KJ5hH/37HegCkBWmd1ohdFfXn492I8MSJeGTdZLwl2ZiIzvuxK9tPysLhDmjyW0RAkqMLIGJ0IVQrTbeE3bJpUi27O6fC+Ahj+NPi5JG76DgTjAiknPH0S96AAn75v+fx7s+f68PFEB/VMBwXm3PUCE0Ot5lebZ9YT/Ujh/40/G7CCqxYPI8TDkbCCGLohQwU9196jTXg/Kv6ePOKtzKrlKsRG07rnz01qfwttkFQcA47ypWWPbhoM3+5TtHFvTjN3oK28vEOFKI0s4at42ekV+hUn5BJ5klj1XoLPJC2vaKjRK8qVpSlwxE8ZPuvg8vWOYYGq6tZ77mM8+CYhcKzq9LtTPfDEvDsvEfHMEcqr+v7snVqDu/wmm+LR4IPME6ASUggZKrFRZL5I/uW8TDOOwTLLOy0evoFWYoqXWIKp31xBOPQZ9+fAd4zoK
  template:
    metadata:
      creationTimestamp: null
      name: deadlock-mod-manager
      namespace: default
    type: opaque
