---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kick-together
  namespace: default
spec:
  encryptedData:
    NODE_ENV: AgAoTIvNueuzffRgcDh93g33s8x4UhmYiw9k/N4fHm5rxlG2zFGLt+gx1tSntJGogxJSmdSnQMl4AsLzu08oIawShqyHGFRKlYE8xZEC53tT7FUpvZfSbdiWRXJ1w22GYjd3aZInEsqVgi6wRZG5F5fcyX4yuWNhErn4hi+ygA0ufsV+jPabSBANwwWMpkZr6D8PiFM2hdgD0TWY1MuXhRhUvu28P15fQM7yzGI5Vh8cv3nhqB1nXz7gPsa4NT+WyGjxF070jo6mHRihEYLuO9eh51nAFMQXGfIi1dc8mOPl1/UputPhUl5I6HfZylG0/L8RXzNBiI1QS1c44YtQ2ERK4KyELe4AkoRIF5VR/JhN3Q1p0E/hZgfTAVnXBYfrSnT4uEhMEXpvaZ8Vm6UkXwbNXFEsHSAdgZhH15TTRBl3pAOSh+V+CBFhheFbn1D5lJn6l0RMGiQrZaEPZfw5xxSvgJ43SxdA4TkkmpBc2SEjSOjA7bBr6lVuGDlDcbhR7c438V48e/QMx7uoi4W2R/4PPXwmzJeWY715ykghpxPskTAeZ9NWSimoePOyQ+UTrTS13ScPjWQnG79xXnobAVk2WccmU0Kj1QSj8GI01jr0qZm6toctaT4SbvUqbmotc0s0K93zhHM19lWS/gS+YaUxLXuTpbUGSuHs5qo6kf3+YpOZNsg9u2HqBgDG1M+hL8gTBUanT4JHCSDi
    PORT: AgAObSJKfBnmJfmP4FI599LB4eaYmCQAmN2TvT0qnnqfzgMeYxNsTJSKN08ExeOVO1ST5YNkWt+HN418XBu7AivvtxKQwatlJzUeUcpWbQs1lYrG6Q0++pCxuAq5VrWAb05xGT5Y1+G2ytIF+LCsmfcVY481RmIHoI3oXq3YPReiNURR65NCc7x8G2Dl7mAa+qRAhlutEdcWJXO3j7V0GYtCBkHEbiLdg79riaG2VhQfRBmjiyhDaGbS29KCERoxvOGZfpXPFhBxX1km0/2h0LKc86D+dZMLiUE3zkgoxOORuFKM7olw5BBnTyPal24uW2fk9KRifS4jVA+ffaTezq9/asPc5csMe9hp5njE5JnzVKcR13xSIjFznLCgvuxBBhpA9OldW7IdqCMlcqnzrZZYVkW5rAx4QWOBmNFGAyx0YuSBWj5LzgZFj52Py4IZu3Pmr320FwPmCmiMVLzPQLpm50sq7xsBRn3uAoA+UbnT1zUQW4kLrybKN12X+k1iZbu+oGnlz7Tq7K9i/ouMirN2QWvS89xFS6EHWXs9OkXVnTDyrfxlqjOmsGR5fSYL4vNqbfP6aXtT0szt/P5+kuLb2djxDZWu9mRagbjxsLrOY81OhnE23zVoS5cAPqxQmMqkj8KI82Ho35Sk/c1WGCb5yrF6xmsDJmJpwClg/if2JZNnEBrNNNB2ToHGk/ZDphptkeol
  template:
    metadata:
      creationTimestamp: null
      name: kick-together
      namespace: default
    type: opaque
