---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: default
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgA/fyOE8c9QjrAoQqfFy+2Xn/byFUs5cLTwUKI4wMuzp4VISMp6OeupgYbQNbS+4HFfsihj+/IukhDVoxxdDiahfG2/tIpfhm39jTxjj0T8end7gOBWlYMMYj6/1lYXLptH785Op/zZR4XSodjFq63O86LDh6rEzzdbrWRZ1cE8VfDAJcA6vLdgq5+uQk1fnMVCc9thraT9+2pg3bf2B1T1tdjdCVFWIGJJ2fg2z/THsAxTCMTrs9x3mFrjF1LxIXqhl6zWKPsBJzuz6Igqlkrx1wueAG7OrzTQRPagpt1lUQN89Ua7fSYgnjWbcT6dwgG091/mThpJHzsYgVX6LhfJU7/QZOd1Ly6tXJhGeHTRQZdvz5BOPzW2r6y9GKDqWdT+zCq2YoQ0RrsuK/VsdVCpUcl9tigZJXQYjyY20ptJSfytUKPpTiv2iWpqissOc/4bJalcdfbuCEs1+MW6zFZJYxz6/+JEqbss4WBoksG1059XyuPSIH/EETiUCYG88q25ZA3hXWsZ9cIoTPS6uxIC24BmuPRerbQ2r1vzam36TbLCtqTXSrOykAtt1SBFEg75U9JbUOvAZlnmeMRCopVE97mWN9EHqwa5DFw8RELHS44Wv287GF1Qpw4pBcWXYrmmDMFafBLCOxHNh1GuMOcR9hhJCu8Pabp46igG6cc9U3s/BZvG6wTGcWScNaaJgzUBr/DEfT8O36Hse3bS+JPA
    MINIO_ROOT_USER: AgCZ97CGzULI7MT/yaFileygdHf8vWA6Tt5UPGdg7ycU75cvmzQa5o4mKoa9m1BAABLrOdvUsIhgcS8zWk2Lt+QsWs6h+DgghjK3oXEEGTX3egTp3W+kT3FHkg9W6LbwciZ/esni673F2HloJC6hPnjRKGvxyESxq+ghnZ6CLaPu6Fx1SE/b26dC3JwBfPRnGW3GI6reWFwFfqDwVcgk2FXwLWtAt6stmTowVDAgrel7ZVIAO72U0pKeMNUnEwjMxKrKFHo3uG0w4u1RydPFg6GqxXhjSVySAOkNNtw+5OIZqbRbuVu45NJXTKLNt67u6e1XZ5r5Um/nI1kCsY59jcxjGKyW97LE/u2bIiWrOIPvXTaHqwpyhE7ouGYoXwJg32uG0aJUAaPlb1FYQ9pE5nNTt2MXUV4TOpxBgCRGT523L4TBocn0R2vAwOYbMNIdz9EAV8HoArmO/IgWRUAgLn0YgtA73zyEkU3OuEjO/SrpGD87k6x/3gTw1E685C3j15Wv9wLkJ38Cpu0Bd3nq9nMjEygO3a5CBG3HfeYfzoUr3t2I4C4H1ajD3jOSiqHTCfWCPrl1gC3sw5IkQ3eV0jHPl0WPTjJwBXKzEiHW2t2hFdokKOm5eVj40DTiKZyZLgf811hxyjcdfT/kavrxCJuXz8vCSNq2qUSsclzj+AXXaLmO60VhEnwiF7v4jPbDTDzWTCwgQJpW1ljV
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: default
