{{- $port := .Values.deployments.web.port | default 80 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-monitor-service
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-monitor-service
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-monitor-service
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: monitor
    spec:
      containers:
        - name: monitor
          image: stormix/huginn-monitor:latest
          ports:
            - containerPort: {{ $port }}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
          {{- if .Values.deployments.web.readinessProbePath }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployments.web.readinessProbePath }}
              port: {{ $port }}
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.deployments.web.memory }}
              cpu: {{ .Values.deployments.web.cpu }}
            limits:
              memory: {{ .Values.deployments.web.memory }}
          envFrom: {{ .Values.envFrom | toYaml | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.deployments.web.env }}
            {{- .Values.deployments.web.env | toYaml | nindent 12 }}
            {{- end }}
            - name: PORT
              value: "{{ $port }}"
            - name: APP_PARTITION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-collector-service
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-collector-service
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-collector-service
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: collector
    spec:
      containers:
        - name: collector
          image: stormix/huginn-collector:latest
          ports:
            - containerPort: {{ $port }}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
          {{- if .Values.deployments.web.readinessProbePath }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployments.web.readinessProbePath }}
              port: {{ $port }}
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.deployments.web.memory }}
              cpu: {{ .Values.deployments.web.cpu }}
            limits:
              memory: {{ .Values.deployments.web.memory }}
          envFrom: {{ .Values.envFrom | toYaml | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.deployments.web.env }}
            {{- .Values.deployments.web.env | toYaml | nindent 12 }}
            {{- end }}
            - name: PORT
              value: "{{ $port }}"
            - name: APP_PARTITION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-writer-service
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-writer-service
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-writer-service
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: writer
    spec:
      containers:
        - name: writer
          image: stormix/huginn-writer:latest
          ports:
            - containerPort: {{ $port }}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
          {{- if .Values.deployments.web.readinessProbePath }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployments.web.readinessProbePath }}
              port: {{ $port }}
          {{- end }}
          # NOTE: We avoid putting a limit on CPU since Kubernetes throttling kills performance and CPU averages
          # tends to be low, so we can allow some pods to burst when needed. Adjust as you see fit.
          resources:
            requests:
              memory: {{ .Values.deployments.web.memory }}
              cpu: {{ .Values.deployments.web.cpu }}
            limits:
              memory: {{ .Values.deployments.web.memory }}
          envFrom: {{ .Values.envFrom | toYaml | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.deployments.web.env }}
            {{- .Values.deployments.web.env | toYaml | nindent 12 }}
            {{- end }}
            - name: PORT
              value: "{{ $port }}"
            - name: APP_PARTITION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-kick
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-kick
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-kick
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: kick
    spec:
      containers:
        - name: kick
          image: stormix/huginn-kick:latest
          ports:
            - containerPort: 3000
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          resources:
            requests:
              memory: {{ .Values.deployments.web.memory }}
              cpu: {{ .Values.deployments.web.cpu }}
            limits:
              memory: {{ .Values.deployments.web.memory }}
          envFrom: {{ .Values.envFrom | toYaml | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.deployments.web.env }}
            {{- .Values.deployments.web.env | toYaml | nindent 12 }}
            {{- end }}
            - name: PORT
              value: "3000"
---
# Services for each deployment
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-monitor
spec:
  type: ClusterIP
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-monitor-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-collector
spec:
  type: ClusterIP
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-collector-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-writer
spec:
  type: ClusterIP
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-writer-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-kick
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-kick