---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud-csi
  namespace: kube-system
spec:
  encryptedData:
    token: AgA5HwVthTM4/rDCr7GTfcy1WnEIp7gpfVUNoNEnPuEZ3+B5yTmkLei4HyxN6rivLw5/13bcUQBNBXr2yxru09NEx1YjGuxhgQynDpq+E8ABUf782vnfwNPq1qRnJxycljUll3hpWvt9sMqa0Ln4dmn7jXxwrKQxc+pT626wWPtS7uaZvsG6OpqQXW5bfJO7gSF/bu92hJZG8Xt2Ypz5tPjsMappuJVqKMs260/2jxTNbgYLXbm5Nq+zSPl3/OJ+/rKX7RBqmcGleQK75NoOl9APP0I9pQJOUp2bDziPSQOpt7oHkXBCM0rLpCIeFEVf42Et2jY0iMOzw5UbG5gODR6Aaxm4sqm9SMqsK+p2svOTReW48XW2zvNZE2bBDCd78SsIvrlOSs6HIXik/WbwcrA4tQnHsH5ONxg8BTA/jr7TIPWuptbD3/b6lw0IiXDwH9bBtPO7kiLQvBIl81gUAM99cOyxmZkKEORvNlct7S+4ld9i1hxdyML73FRRlmZ3yHaG4mcth+4bCw3AXxdZpbPDZ6yl0k4Dz/nEF5oYMYxM7T73Y/EEs/Pw1W+B7Sk3yRNa7sWjeDrNDSsR4Tl0jiCPYtserVYqMN7fxUgQ9oO9b/kcLogy0T561PiMJyOFw0uCd3yP7LfOblrJdxKbwnffEoK/7rB293JkAyzt5W8+S5s5BdlQbaY0VrqOGrd9LWuh0deeeSXVZyQqSPqhX1C+9MSi7cX3lcgPRUWShSo6lURM5gGcWi+H1jMGIyE6dTjLVVoVK1+lwlzSKRwzBZGJ
  template:
    metadata:
      creationTimestamp: null
      name: hcloud-csi
      namespace: kube-system