deployments:
  web:
    replicas: 1
    memory: 512Mi
    cpu: 250m
    env:
      - name: RUST_LOG
        value: "info"
    readinessProbePath: /health # when this path returns 200 the pod will be considered ready
    port: 8080

envFrom:
  - secretRef:
      name: huginn
env:
  - { name: APP_REDIS_URL, value: "redis://twitch-stalker-redis-master.default.svc:6379" }
  - { name: APP_PARTITION_ID, value: "0" }
  - { name: APP_KICK_URL, value: "http://huginn-kick.default.svc.cluster.local:3000" }
  - { name: RUST_LOG, value: "info" }